### ISSUE TITLE
Object of type 'set' is not JSON serializable

### ISSUE THREAD

**Issue by chaoyue729** [benmaier/netwulf#11]
when i try the third example
`import networkx as nx
   ...: import community
   ...: from netwulf import visualize
   ...:
   ...: G = nx.random_partition_graph([10,10,10],.25,.01)
   ...: bb = community.best_partition(G)  # dict of node-community pairs
   ...: nx.set_node_attributes(G, bb, 'group')
   ...:
   ...:

In [6]: visualize(G)`

**Comment by benmaier** [comment]
yup, I fixed that yesterday but haven't had time to push to PyPi so far. I did that now, so this should work with version 0.0.13

**Comment by chaoyue729** [comment]
> yup, I fixed that yesterday but haven't had time to push to PyPi so far. I did that now, so this should work with version 0.0.13

i have already update the package, Thanks !
another issue is how to close the session in ipython?

**Comment by benmaier** [comment]
in the python or IPython shell, the KeyboardInterrupt-signal closes the session, i.e. Ctrl+C. In a Jupyter notebook, press the stop button!

**Comment by benmaier** [comment]
closing this, feel free to open a new one for other issues
