### ISSUE TITLE
`Post to Python` does not close the window anymore and also does not stop the server anymore

### ISSUE THREAD

**Issue by benmaier** [benmaier/netwulf#15]

**Comment by ulfaslak** [comment]
Noooooooooooo.....

**Comment by benmaier** [comment]
haha

**Comment by ulfaslak** [comment]
we are better than this

**Comment by benmaier** [comment]
it's probably the sweetalert tbh.

**Comment by ulfaslak** [comment]
It actually works for me :).

**Comment by benmaier** [comment]
great ..............

**Comment by benmaier** [comment]
somehow, sweetalert does weird things for me now.

**Comment by benmaier** [comment]
found it. You seem to have switched to `sweetalert2.all.min.js` in `index.html`? But the functions in `vis.js` don't seem to have changed, at least the `post to python` did not. They're still written for sweetalert v1. Is there any reason you changed to v2?

**Comment by ulfaslak** [comment]
Hmmm.. I changed this long ago. v1 is not supported (developer gone missing), so v2 is the thing people are using now. I was getting errors with v1, so I switched.

**Comment by benmaier** [comment]
okay... looking at the API of swal2 (https://sweetalert2.github.io/) I'm actually suprised that the code wirtten for v1 works at all, because it seems to be very different to what is demanded (e.g. `Swal.fire` vs `swal`). I agree that in the long term the alerts should be replaced by v2 alerts but could we for now go back to v1 so it works without us doing any major work? :D what do you think?

**Comment by ulfaslak** [comment]
Yeeeah ok you're right this is all messed up. We can switch, but I was getting errors before, so it will probably cause some errors again. For the sake of development, let's switch now, and then move to v2 later.

**Comment by ulfaslak** [comment]
I updated the code in https://github.com/ulfaslak/network_styling_with_d3/ to sweetalert2. netwulf works fine for me now.

**Comment by benmaier** [comment]
whoa, super fast! works like a charm, thanks :)

One thing: the alerts have a serif font, now. Do they have that on your machine, too?

<img width="333" alt="Screen Shot 2019-04-11 at 07 53 27" src="https://user-images.githubusercontent.com/10728380/55962902-00506d80-5c2f-11e9-9646-de764e20b6ad.png">

I could try changing that in the CSS if you agree. I bet it's something on my computer again though haha

**Comment by benmaier** [comment]
saw that: https://github.com/sweetalert2/sweetalert2/issues/846 

would you mind me changing the font to some sans-serif like helvetica, arial ?

**Comment by ulfaslak** [comment]
Yes please go ahead, not a fan of Serif (doesn't look like that on my machine though).
