### ISSUE TITLE
the config-dict parsed to `visualize` is not respected in the visualization anymore

### ISSUE THREAD

**Issue by benmaier** [benmaier/netwulf#16]

**Comment by ulfaslak** [comment]
Probably my doing. Will have a look

**Comment by benmaier** [comment]
already working on it!

**Comment by ulfaslak** [comment]
Oh, no I think it's super simple. I changed some of the names of keys in the config dictionary, because I didn't like the old ones. Maybe that's just the problem?

**Comment by benmaier** [comment]
ah. However, even "Node size" doesn't work anymore. I think, Reflect.ownKeys is not working properly for some reason.

**Comment by benmaier** [comment]
wth. it seems like "Path to file" is the only "ownProperty" that the config dictionary has... that's super weird.

**Comment by ulfaslak** [comment]
Is the change I made to parse_options.js reflected in the version of the webapp that netwulf is using? Check out https://github.com/ulfaslak/network_styling_with_d3/blob/master/parse_options.js

**Comment by ulfaslak** [comment]
I made that change because I needed the thing to work if you only input data (and not config)

**Comment by benmaier** [comment]
yes

**Comment by benmaier** [comment]
makes sense.

**Comment by ulfaslak** [comment]
I can't reproduce :/

**Comment by benmaier** [comment]
so if you for instance start it with `config={'Node size':100}` the nodes are huge?

**Comment by ulfaslak** [comment]
Ah you're right it doesn't work for me too.

**Comment by ulfaslak** [comment]
Nono it works, just use 'Size' instead of 'Node size'. I changed that. It was more intuitive to call it that as it was already under the "Node" tab.

**Comment by benmaier** [comment]
Apparently, I was behind 1 commit :( . It still does not work for me, though.

also, I agree that the new names make sense for the GUI, but for the Python config, they're relatively non-descriptive now. Consider

```python
visualize(G, config={'Size': 10, 'Color': '#000000'})
```

size refers to the nodes but color refers to the links. I think this is pretty unintuitive.

**Comment by benmaier** [comment]
I'll check in the evening what's going wrong with Reflect.ownKeys on my machine. annoys me to no end :(

**Comment by ulfaslak** [comment]
This is technical debt. Really we should have generic names for each parameter and then print something different in the visualization. I'll make an issue for this and solve it soon.

**Comment by benmaier** [comment]
yeah you're right, this would be the proper way. Thanks :)

**Comment by benmaier** [comment]
works now!!! thanks, ulf!
