### ISSUE TITLE
Add community guidelines

### ISSUE THREAD

**Issue by leouieda** [benmaier/netwulf#17]
Hi @ulfaslak @benmaier, are there community guidelines for this project? For example, a contributing guide (usually `CONTRIBUTING.md`) and a code of conduct (usually `CODE_OF_CONDUCT.md` from [Contributor Covenant](https://www.contributor-covenant.org/)). I couldn't find anything in the repository or the documentation. 

These are required for the JOSS submission (openjournals/joss-reviews#1425) and are usually straight forward to add. So I though I'd give you a head start before the review starts :slightly_smiling_face:

**Comment by benmaier** [comment]
quote

> Community guidelines: While there are some development notes on how to update the front-end from it's upstream directory when developing, there are no clear guidelines on Github (in the readme or otherwise) or in the documentation on how to best jump into development or open a pull request for bug fixes or new features. Additionally, there is no documentation on how to report issues and it's implicitly implied that the user should open a Github issue. If that's the desired error reporting behavior, this should be made more explicit in the documentation. If Github issues is the desired mechanism, it may be beneficial to the developers to open issues for some of the behaviors noted here - for the authors: let me know if you'd like me to open issues for the items identified in the Functionality section above.

**Comment by benmaier** [comment]
Added. We should further discuss whether to add something about contributing in the documentation, too.
