### ISSUE TITLE
Let `visualize` be run without argument such that the interface opens and a file can be loaded manually

### ISSUE THREAD

**Issue by benmaier** [benmaier/netwulf#21]
as suggested by @vc1492a in https://github.com/openjournals/joss-reviews/issues/1425

> Some potentially useful functionality would be to allow a user to start the visualization interface without the need to pass a graph object into visualize(). This may be useful in the case where the user has a file that they wish to examine and want to upload, but may not want to load first within the Python environment. By making the graph object an optional argument, the user could start the visualization interface and then explore one or more files through the upload functionality. This would be a nice feature in future releases but isn't necessary to address as part of this review. Consider opening an issue with the tag enhancement.

**Comment by benmaier** [comment]
I think I disagree here. Loading a network from a file in Python takes usually [a single line of code using networkx](https://networkx.github.io/documentation/latest/auto_examples/basic/plot_read_write.html#sphx-glr-auto-examples-basic-plot-read-write-py) which should be simple enough and lines up with the philosophy that everything besides styling the network should be done programmatically. In fact, it seems that version 0.0.14 on PyPI contained outdated code which actually let the user upload files. In the actual (now updated version 0.0.16), these parts of the UI are suppressed in the interface started in Python and only shown in its online version (see https://ulfaslak.com/works/network_styling_with_d3/index.html). I apologize for the mismatch of the interface in the PyPI-version and the latest github-commit. This shouldn't have happened.

**Comment by benmaier** [comment]
tagging @ulfaslak to ask for comment

**Comment by ulfaslak** [comment]
I'm with @benmaier on this one. It's a nice idea, and I'm happy you bring it up, because it does offer insight into what interactions feel intuitive, but I think it's going to create more confusion than utility. Moreover, the `visualize` function can actually take a dictionary object as input, so if one had such an object stored locally, the better way to visualize it in `netwulf` would be to load and serve it as input to `visualize`.

**Comment by vc1492a** [comment]
@benmaier @ulfaslak Thanks for the commentary here - as you both mentioned, it looks like the newer version no longer allows users to upload files themselves in the interface and thus makes sense to require the user to pass some sort of object to initialize the visualization interface.
