### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by benmaier** [benmaier/netwulf#26]
openjournals/joss-reviews#1425

> Automated tests: I did not see any automated tests in this repository that could be used to verify the functionality of the software. Revisions of this work should include a series of unit tests that can be used to verify the functionality of the software, through testing of function outputs, input and output formatting, etc. There are a variety of ways to write and use unit tests in Python, two of which are the pytest and pytest-cov packages - the former allows developers to execute unit tests (with helpful extensions for writing tests, too) while the latter provides functionality to pytest for coverage statistics, e.g. which lines of code your unit tests cover and the percentage of lines in each file (and overall, the package) that is covered by the written unit tests (this coverage statistic could be reported in readme.md). Additionally, if you're looking to have others contribute to the project more easily in the future consider setting up a continuous integration pipeline that will automatically run tests and report the test results (e.g. using Travis CI) and coverage (e.g. using Coveralls) with any pushes to master or dev and for any pull requests opened by open-source contributors. This pipeline would ease the burden on making sure new additions and/or changes to software work as intended, and would also allow maintainers to formally test against every version of Python 3 that should be supported. This would allow the authors to state "this software works in Python versions 3.5 - 3.7" as opposed to simply stating "works in Python 3".

**Comment by benmaier** [comment]
My main problem with this point is that the main purpose of the package is the interactive user-interface. I'm a bit lost on how to introduce automated testing for user interaction. @ulfaslak comments?

**Comment by ulfaslak** [comment]
I see the point, especially for making contribution easier. The problem here is that the key functionality really has no immediate output, at least not without user interaction. To write automated tests, we would have to fill in the interaction step with something like `selenium` webdriver, but I can easily see that spinning out of proportion and introducing more obscurity than validation.

**Comment by benmaier** [comment]
added testing functionality
