### ISSUE TITLE
Can't post visualization back to python

### ISSUE THREAD

**Issue by wanderingashenvalewisp** [benmaier/netwulf#44]
Hi developers,

i am using your cool tool to visualize a network. But i don't have the option to post my visualization back to python as you have in your tutorial on [https://netwulf.readthedocs.io/en/latest/python_api/post_back.html](https://netwulf.readthedocs.io/en/latest/python_api/post_back.html) Instead i have the option to upload or save a json. [Screenshot of my display](https://ibb.co/t3fNKvB)

I have tried to reinstall your package but it still only gives me the option to upload or save a json file.
What am i doing wrong? 

kind regards

**Comment by wanderingashenvalewisp** [comment]
For some reason it works now :) 
Awesome application that you guys have made. 
Such a nice feature that you can model the network inside the app and then get the coordinates of each node back in python. 
Makes plotting networks in matplotlib so much easier, thanks again!

**Comment by ulfaslak** [comment]
Thanks for using it! Happy that it works for you :).
