### ISSUE TITLE
is netwulf supports directed networkx ?

### ISSUE THREAD

**Issue by zoldaten** [benmaier/netwulf#47]
hi!
how to add arrows and weights to graph to visualize ?

**Comment by benmaier** [comment]
Arrows are not implemented yet, but on the list for v0.2. Weights are handled automatically, just add them to the edges with a "weight" keyword: https://netwulf.readthedocs.io/en/latest/visualization/init.html?highlight=weight#links

**Comment by zoldaten** [comment]
Ok, got it. But is it possible to show weight labels not only on plot in Jupyter but in visualization also ?
Something like this:
labels = nx.get_edge_attributes(G,'weight')
nx.draw_networkx_edge_labels(G,pos,edge_labels=labels)

**Comment by benmaier** [comment]
not atm, no. @ulfaslak is there a feature like this planned for v0.2?

**Comment by ulfaslak** [comment]
Not a bad idea. Will add it to the to-do panel!
