### ISSUE TITLE
how to make .exe in Windows with pyinstaller and netwulf included [SOLVED] 

### ISSUE THREAD

**Issue by zoldaten** [benmaier/netwulf#48]
Hi ! 
While packing netwulf in windows with **pyinstaller myscript.py -D** i got errors.
The first one was that matplotlib wasn't work correctly so i downgraded it to **matplotlib==3.0.3**
Than i fixed mathplotlib in its dir '/site-packages/matplotlib/mpl-data/matplotlibrc': TkAgg to Agg following this issue:
_https://stackoverflow.com/questions/20582384/importerror-no-module-named-backend-tkagg_
Than i packed my script again **pyinstaller myscript.py -D** and had error: **distutils.errors.DistutilsFileError: cannot copy tree ...**
So i copied dir netwulf/js from native package to my package dist dir: **dist\myscript\netwulf\js** 

After that my script.exe works correctly using netwulf package!

**Comment by benmaier** [comment]
Thank you! Might be useful for others. I'll close this then.
