### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by zoldaten** [benmaier/netwulf#49]
Great thanks for your program! I look at it after d3.js, networkx.
But have some questions:
1 how to change canvas in code (width & height) ?
2 how to load edgelist to make a layered network (like in webweb) ?
3 how to add weights to show like in d3.js, networkx ?
(labels = nx.get_edge_attributes(G,'weight')
nx.draw_networkx_edge_labels(G,pos,edge_labels=labels))
4 is it possible to switch on edges i want to watch the path from one node to another ?
5 how to find nodes (edges) names like in webweb and hightlight them ?
6 is is possible to make undruggable nodes that i touched not freezing all nodes at once ?

**Comment by benmaier** [comment]
It seems you're looking for an interactive network analysis solution. As we write in the paper (https://joss.theoj.org/papers/10.21105/joss.01425), netwulf is not supposed to be that. I suggest to use webweb or other tools.
