### ISSUE TITLE
POST picture back to Python such that it's shown in the Jupyter notebook, if one is used

### ISSUE THREAD

**Issue by benmaier** [benmaier/netwulf#8]
Post picture data to server
* https://stackoverflow.com/questions/34972072/how-to-send-image-to-server-with-http-post-in-javascript-and-store-base64-in-mon

Display image in jupyter notebook
* https://stackoverflow.com/questions/32370281/how-to-embed-image-or-picture-in-jupyter-notebook-either-from-a-local-machine-o

Find out wether the whole thing is running in a Jupyter notebook
* https://stackoverflow.com/questions/15411967/how-can-i-check-if-code-is-executed-in-the-ipython-notebook

**Comment by benmaier** [comment]
@ulfaslak yo, I wrote a function which reproduces the figure in matplotlib. see https://github.com/benmaier/netwulf/blob/master/netwulf/tools.py#L72

I also figured out a way to post the js-created png back to python, but I think it's nicer if we don't display the js-png but recreate the figure in matplotlib. That way, one can actually still do stuff with the figure and possibly save the whole thing as a PDF or what not. What do you think? Display js-png or redrawn matplotlib figure?

**Comment by benmaier** [comment]
Redrawing in matplotlib actually works great. However I have no doubt the posted picture should be available in the API somehow

**Comment by ulfaslak** [comment]
Sorry for reacting so slowly to this. I think the latter (matplotlib) solution is nicest! Especially because it enables exporting in vector format, which is a serious limitation is using canvas. So this kinda solves two problems at once :D!
